baseURL = "https://mnml.blog/"
languageCode = "en-us"
title = "mnml.blog"
paginate = 10
copyright = "James Evans"
disqusShortname = ""
googleAnalytics = ""
ignoreErrors = ["error-remote-getjson"]

[author]
  name = "James Evans"
  profile = "https://mnml.blog/about/"
  email = "jwhevans@hotmail.com"
  nickname = "James"

[params]
   author = "James Evans"
   description = "In a society that profits from your self doubt, liking yourself is a rebellious act."
   github = "https://github.com/jwhevans"
   twitter = "https://twitter.com/jwhevans"
   microblog = "https://micro.blog/jwhevans"
   webmentionEndpoint = "https://webmention.io/mnml.blog/webmention"
   pingbackEndpoint = "https://webmention.io/mnml.blog/xmlrpc"
   micropubEndpoint = "https://example.com/webmention/micropub"
   email = "jwhevans@hotmail.com"
   

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "posts"
    identifier = "posts"
    url = "/posts/"
    weight = 1
    
  [[menu.main]]
    identifier = "river"
    name = "river"
    url = "/river/"
    weight = 2

[taxonomies]
  tag = "tags"

[permalinks]
  posts = "/:year/:month/:slug/"
  
[services.rss]
  limit = 20
  
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
    
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
